"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {OFFER,TRACKS,FAQS} from "../lib/content";
const money=(n:number)=>new Intl.NumberFormat("ar-DZ").format(n)+" دج";
const Head=({tag,title,sub}:{tag:string,title:string,sub?:string})=><header className="head"><span>{tag}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</header>;
const Book=()=> <div className="book"><div>BAC<br/><b>MASTER</b><i>2027</i></div><p>نماذج البكالوريا<br/>مع الحلول</p><small>حسب شعبتك</small></div>;
export default function Home(){const router=useRouter(),[track,setTrack]=useState(""),[sticky,setSticky]=useState(false);useEffect(()=>{const f=()=>setSticky(scrollY>600);addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);const order=()=>document.getElementById("order")?.scrollIntoView({behavior:"smooth"});const choose=(t:string)=>{setTrack(t);document.getElementById("offer")?.scrollIntoView({behavior:"smooth"})};const submit=(e:FormEvent)=>{e.preventDefault();router.push("/order-success")};return <main>
<section className="hero"><div className="wrap grid"><div><span className="pill">Candidate 01 — محتوى تجريبي</span><p className="brand">BAC MASTER 2027</p><h1>حضّر للباك <em>بالتطبيق،</em><br/>مش بالمراجعة العشوائية.</h1><p className="lead">نماذج بكالوريا مختارة مع الحلول، منظمة حسب شعبتك، باش تتدرب وتراجع بطريقة أسهل.</p><div className="price"><strong>{money(OFFER.price)}</strong><del>{money(OFFER.oldPrice)}</del><b>وفر {money(OFFER.oldPrice-OFFER.price)}</b></div><button className="btn" onClick={order}>اطلب نسختك الآن</button><p className="muted">معلومات التوصيل والدفع تؤكد لاحقاً من العميل.</p></div><Book/></div></section>
<section id="tracks" className="section"><div className="wrap"><Head tag="اختيار سريع" title="اختر شعبتك 👇" sub="اختيارك يبقى محفوظاً حتى نموذج الطلب."/><div className="tracks">{TRACKS.map(t=><button key={t} className={track===t?"track active":"track"} onClick={()=>choose(t)}>📘 <b>{t}</b><small>{track===t?"تم الاختيار ✓":"اختر هذه الشعبة"}</small></button>)}</div></div></section>
<section className="section soft"><div className="wrap narrow"><Head tag="المشكلة" title="راك تراجع للباك... بصح هل راك تتدرب عليه؟"/><div className="pain"><p>عندك عشرات الدروس.</p><p>مئات الفيديوهات.</p><p>مواضيع موزعة في أماكن مختلفة.</p><strong>وكل مرة تسقسي: منين نبدأ؟</strong></div><p className="center">BAC MASTER يجمع لك التدريب والحلول في مكان واحد، حسب شعبتك.</p><button className="btn centerBtn" onClick={()=>document.getElementById("tracks")?.scrollIntoView({behavior:"smooth"})}>اختر شعبتك</button></div></section>
<section className="section"><div className="wrap"><Head tag="نظرة على المنتج" title="شوف واش تلقى داخل الكتاب" sub="المساحات التالية ستستبدل بصور العميل الحقيقية."/><div className="previews">{["الغلاف","صفحة داخلية","نموذج موضوع","صفحة الحل"].map((x,i)=><div className="preview" key={x}><span>0{i+1}</span><b>صورة {x}</b><small>PLACEHOLDER</small></div>)}</div><button className="btn centerBtn" onClick={order}>نحب نسختي</button></div></section>
<section className="section dark"><div className="wrap"><Head tag="بلا تعقيد" title="كيفاش تطلب؟"/><div className="steps">{[["01","اختر شعبتك"],["02","عمّر معلومات الطلب"],["03","استلم وابدأ التدريب"]].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3></div>)}</div><p className="muted">تفاصيل التوصيل النهائية في انتظار تأكيد العميل.</p></div></section>
<section id="offer" className="section offer"><div className="wrap grid"><div><Head tag="العرض الذهبي — مؤقت" title="واش راح تحصل عليه؟"/>{["📘 BAC MASTER 2027 — نماذج + حلول حسب الشعبة","🎁 خطة مراجعة BAC — Placeholder","🎁 Checklist يوم الامتحان — Placeholder","🎁 Bonus رقمي — Placeholder"].map(x=><p className="stack" key={x}>{x}</p>)}</div><div className="offerCard"><p>سعر Candidate 01</p><del>{money(OFFER.oldPrice)}</del><strong>{money(OFFER.price)}</strong><small>القيم مؤقتة حتى تأكيد العميل</small><button className="btn" onClick={order}>استفد من العرض</button></div></div></section>
<section className="section soft"><div className="wrap"><Head tag="الثقة" title="وش قالو الطلبة؟" sub="لا توجد شهادات مختلقة. هذه أماكن مخصصة للـ Reviews الحقيقية."/><div className="reviews">{[1,2,3].map(i=><div className="review" key={i}>💬<h3>رأي زبون #{i}</h3><p>Screenshot / Video testimonial حقيقي يوضع هنا لاحقاً.</p><small>PLACEHOLDER</small></div>)}</div></div></section>
<section className="section push"><div className="wrap"><h2>جاهز تبدأ التحضير؟</h2><p>{track?"نسختك المختارة: "+track:"اختر شعبتك واطلب BAC MASTER 2027."}</p><strong>{money(OFFER.price)}</strong><button className="btn" onClick={order}>اطلب الآن</button></div></section>
<section className="section"><div className="wrap duo"><div className="trust">🛡️ <div><h2>اطلب براحة</h2><p>سياسة الضمان والاستبدال النهائية توضع بعد تأكيد العميل.</p></div></div><div className="trust">🔥 <div><h2>عرض الدفعة الحالية</h2><p>مكان مخصص لندرة أو مدة حقيقية فقط. لا Stock أو Countdown مخترع.</p></div></div></div></section>
<section className="section soft"><div className="wrap narrow"><Head tag="قبل ما تطلب" title="الأسئلة الشائعة"/>{FAQS.map(q=><details key={q}><summary>{q}</summary><p>الإجابة النهائية في انتظار تأكيد العميل.</p></details>)}</div></section>
<section id="order" className="section order"><div className="wrap orderGrid"><form onSubmit={submit}><Head tag="آخر خطوة" title="أطلب نسختك الآن" sub="النموذج لا يرسل بيانات إلى Backend في Task 01."/><label>الاسم واللقب<input required placeholder="الاسم الكامل"/></label><label>رقم الهاتف<input required inputMode="tel" placeholder="05 / 06 / 07 ..."/></label><label>الشعبة<select required value={track} onChange={e=>setTrack(e.target.value)}><option value="">اختر الشعبة</option>{TRACKS.map(t=><option key={t}>{t}</option>)}</select></label><div className="two"><label>الولاية<input required placeholder="الولاية"/></label><label>البلدية<input required placeholder="البلدية"/></label></div><fieldset><legend>نوع التوصيل</legend><label className="radio"><input required type="radio" name="delivery"/> للمنزل</label><label className="radio"><input required type="radio" name="delivery"/> للمكتب</label></fieldset><button className="btn full">تأكيد الطلب التجريبي</button><p className="privacy">🔒 لا يتم إرسال معلوماتك لأي خادم في Candidate 01.</p></form><aside className="summary"><span className="pill">ملخص الطلب</span><h3>{OFFER.product}</h3><p>الشعبة <b>{track||"لم تختر بعد"}</b></p><p>السعر <b>{money(OFFER.price)}</b></p><p>التوصيل <b>يحدد لاحقاً</b></p><hr/><h3>المجموع: {money(OFFER.price)} + التوصيل</h3><small>سعر التوصيل ينتظر بيانات العميل.</small></aside></div></section>
<footer><div className="wrap"><b>BAC MASTER 2027</b><p>الهاتف وروابط Facebook / Instagram / TikTok: Placeholder</p></div></footer>
{sticky&&<div className="sticky"><div><small>{track||"BAC MASTER 2027"}</small><b>{money(OFFER.price)}</b></div><button onClick={order}>اطلب الآن</button></div>}</main>}